name: Run Combinations Script

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  run-combinations:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'  # Specify the Python version you need

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests playwright faker

    # Step 4: Install Playwright browsers (for Chromium, Firefox, etc.)
    - name: Install Playwright Browsers
      run: |
        playwright install

    # Step 5: Run the Python script (combinations.py)
    - name: Run combinations.py script
      run: |
        python combinations.py

    # Optional: Upload the output (e.g., screenshots or CSV) as workflow artifacts
    - name: Upload artifact (screenshot and CSV)
      uses: actions/upload-artifact@v3
      with:
        name: combination-output
        path: |
          full_page_screenshot.png
          combinations.csv
